name: publish

on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the shopify-docker-images
      run: |
        echo $CR_PAT | docker login ghcr.io -u alexandresc --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
